apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devsu-demo-python.fullname" . }}-config
  labels:
    {{- include "devsu-demo-python.labels" . | nindent 4 }}
data:
  DATABASE_NAME: {{ .Values.env.databaseName | quote }}
