apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devsu-demo-python.fullname" . }}-secret
  labels:
    {{- include "devsu-demo-python.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.secret.djangoSecretKey | quote }}
